cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

fyp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('order/', views.OrderView.as_view(), name='order'),    
    path('account/', views.AccountView.as_view(), name='account'),    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
  
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
     path('', views.StaffView.as_view(), name='staff'),
     path('collect/', views.OrderCollectView.as_view(), name='order-collect'),
     path('collect/<pk>/confirm/', views.ConfirmCollectView.as_view(), name='confirm-collect'),
     path('create/', views.ProductCreateView.as_view(), name='product-create'),
     path('products/', views.ProductListView.as_view(), name='product-list'),
     path('products/<pk>/update/',views.ProductUpdateView.as_view(), name='product-update'),
     path('products/<pk>/delete/',views.ProductDeleteView.as_view(), name='product-delete'),
]

staff/forms.py
from django import forms

from cart.models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'nutrition',
            'price',
            'stock_quantity',
            'pickup_location',
            'location_description',
            'produced',
            'expired',
            'primary_category',
            'secondary_categories',
        ]
        labels = {
            'title' :"Product Name",
            'image':"Product Image",
            'description' : "Description",
            'nutrition':'Nutrition Fact (Please line space and separate each nutrition value)',
            "price":"Price (5000 = RM 50.00)",
            "produced":"Produced Date (YYYY-MM-DD)",
            'stock_quantity' : "Stock Quantity",
            'pickup_location': "Pick-up Location",
            'location_description': "Pick-up Location Description",
            "expired":"Expiry Date (YYYY-MM-DD)",
            'primary_category':'Primary Category',
            'secondary_categories':'Secondary Categories'
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'collected'
        ]
        labels = {
            "collected":"Order Collected?"
        }

staff/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse,redirect
from django.views import generic
from cart.models import Order, Product, Category
from .forms import ProductForm, OrderForm
from .mixins import StaffUserMixin


class StaffView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered=True).order_by('-ordered_date')
    paginate_by = 10
    context_object_name = 'orders'

    def get_context_data(self, **kwargs):
        context = super(StaffView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context

class OrderCollectView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/order_collect.html'
    queryset = Order.objects.filter(ordered=True).order_by('-ordered_date')
    paginate_by = 10
    context_object_name = 'orders'
    def get_context_data(self, **kwargs):
        context = super(OrderCollectView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context
    
class ConfirmCollectView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/confirm_collect.html'
    queryset = Order.objects.all()
    form_class = OrderForm
    context_object_name = 'orders'

    def form_valid(self, form):
        form.save()
        return redirect("staff:staff")
    
    def get_context_data(self, **kwargs):
        context = super(ConfirmCollectView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context
    
class ProductListView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/product_list.html'
    queryset = Product.objects.all()
    paginate_by = 10
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context

class ProductCreateView(LoginRequiredMixin, StaffUserMixin, generic.CreateView):
    template_name = 'staff/product_create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context

class ProductUpdateView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/product_update.html'
    form_class = ProductForm
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context

        
class ProductDeleteView(LoginRequiredMixin, StaffUserMixin, generic.DeleteView):
    template_name = 'staff/product_delete.html'
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")
    
    def get_context_data(self, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context

templates/staff/confirm_collect.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="text-center justify-content-center">
<h2>{{orders.reference_number}} collection status</h2>
<div class="my-5 ml-3">
    <form style="color:red" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy}}
        <br/><button type='submit' class='btn btn-primary '>Submit</button>
    </form> 
</div>
</div>
{% endblock content %}

templates/staff/order_collect.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black mb-3">Manage Collect Status</h2>
                <a href="{% url 'staff:staff' %}"><span><</span>Back</a><br/>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                        </h5>

                        <h5 class="card-title">Recent orders</h5>
                        <div class="site-blocks-table" style="overflow-x:auto;">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Collected</td>
                                        <th>Action</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.user.username }}</td>
                                        <td>RM{{ order.get_total }}</td>
                                        <td>{% if order.collected %}Yes{% else %}No{% endif %}</td>
                                        {% if order.collected %}
                                            <td>Collected</td>
                                        {% else %}
                                        <form method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {{ form }}
                                            <td><a href="{{ order.get_collect_url }}" style="color:green;">Collect</a></td>
                                        </form>
                                        {% endif %}                                        
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/staff/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4 class="text-center" style="font-weight:bold">Create a product</h4>
                <form class="mt-3" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary mt-4'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="site-section">
        <div class="container pt-3 pb-5">
            <div class="row justify-content-center">
                <div class="col-md-7">
                    <h2 class="h3 mb-3 text-black text-center" style="color:red;">Delete Product</h2>
                </div>
                <div class="col-md-12 justify-content-center">
                    <h3 class="h5 mb-3 text-center">Are you sure you want to delete this product?</h3>
                </div>
                <div class="col-md-2">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type='submit' class='btn btn-primary'>Submit</button>
                    </form>                
                </div>
                <div class="col-md-1">
                    <a href="{% url 'staff:product-list' %}" class='btn btn-primary'>Cancel</a>         
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/staff/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black mb-3">Staff Portal - Products</h2>
                <a href="{% url 'staff:staff' %}"><span><</span>Back</a><br/>
                <a href="{% url 'staff:product-create' %}">Create a new product</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="site-blocks-table" style="overflow-x:auto;">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Expiry Date</th>
                                        <th>Expired</th>
                                        <th>Price</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in products %}
                                    <tr>
                                        <td>{{ product.title }}</td>
                                        <td>{{ product.expired }}</td>
                                        {% if product.get_date %}
                                            <td style="color:red">Expired</td>
                                        {% else %}
                                            <td style="color:green">Not Expired</td>
                                        {% endif %}
                                        <td>RM {{ product.get_price }}</td>
                                        <td>
                                            <a href="{{ product.get_update_url }}">Update</a>
                                            <a href="{{ product.get_delete_url }}">| Delete</a>

                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3">You don't have any products</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    
                                        {% if page_obj.has_previous %}
                                            <a><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></a>
                                        {% else %}
                                            <a class='disabled'><span>&laquo;</span></a>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <a class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </a>
                                            {% else %}
                                                <a><a href="?page={{ i }}">{{ i }}</a></a>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <a><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></a>
                                        {% else %}
                                            <a class='disabled'><span>&raquo;</span></a>
                                        {% endif %}
                                    
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(function () {
        $("[data-toggle=popover]").popover();
    });
</script>
{% endblock scripts %}

templates/staff/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'staff:product-list' %}">Go back to products</a>
                <hr />
                <h4 class="text-center" style="font-weight:bold">Update product</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary mt-4'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/staff.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Staff Portal</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Welcome, {{ request.user.first_name }} {{ request.user.last_name }}
                        </h5>
                        <a href="{% url 'staff:product-list' %}">Products</a> <br/>
                        <a href="{% url 'staff:order-collect' %}">Manage Collect Status</a>
                        <hr />

                        <h5 class="card-title">Recent orders</h5>
                        <div class="site-blocks-table" style="overflow-x:auto;">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                        <th>Collect Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>{{ order.user.username }}</td>
                                        <td>RM{{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                        <td>{% if order.collected %}Yes{% else %}No{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class='active'>
                                                    <span>
                                                    {{ i }}
                                                     <span class='sr-only'>(current)</span>
                                                    </span>
                                                </li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class='disabled'><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}