cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

fyp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('order/', views.OrderView.as_view(), name='order'),    
    path('account/', views.AccountView.as_view(), name='account'),    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
  
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
     path('', views.StaffView.as_view(), name='staff'),
     path('collect/', views.OrderCollectView.as_view(), name='order-collect'),
     path('collect/<pk>/confirm/', views.ConfirmCollectView.as_view(), name='confirm-collect'),
     path('create/', views.ProductCreateView.as_view(), name='product-create'),
     path('products/', views.ProductListView.as_view(), name='product-list'),
     path('products/<pk>/update/',views.ProductUpdateView.as_view(), name='product-update'),
     path('products/<pk>/delete/',views.ProductDeleteView.as_view(), name='product-delete'),
]

templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black text-center pb-3" style="font-weight:bold">My Account</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                        </h5>
                        <hr />
                        <h5 class="card-title">Actions</h5>
                        <hr />
                        <ul class="ml-3">
                        <li class="card-title "><a href="{% url 'account_change_password' %}">Change Password</a></li>
                        </ul>
                        {% comment %} <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#333{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SurFood {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> 
<body>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="/"><img src="/static/img/logo1.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="{% url 'account' %}" style="color:black;"><i class="fa fa-user"></i> Account</a></li>
                <li><a href="{% url 'order' %}" style="color:black;"><i class="fa fa-history"></i> Order</a></li>
                <li><a href="{% url 'cart:summary'%}" style="color:black;"><i class="fa fa-shopping-bag"></i> Cart</a></li>
            </ul>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li id='Home_Header' class="active"><a href="/">Home</a></li>
                <li><a href={% url 'cart:product-list' %}>Shop</a></li>
                <li><a href="{% url 'cart:summary'%}">Shopping Cart</a></li>
                <li><a href="/contact/">Contact</a></li>
                {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff'%}">Staff</a></li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}" style="color: #7fad39">Login</a></li>
                {% else %}
                <li><a href="{% url 'account_logout' %}" style="color: #7fad39">Logout</a></li>
                {% endif %}

            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
    </div>

    <!--Hamburger End-->
    <!--Header Start-->
    <header class="header">
        <div class="header__top">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="/"><img src="/static/img/logo1.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu pt-5 pl-2">
                        <ul>
                                    <li class=""><a href="/">Home</a></li>
                                    <li><a href={% url 'cart:product-list' %}>Shop</a></li>
                                </li>
                                <li><a href="{% url 'contact' %}">Contact</a></li>
                                    {% if request.user.is_staff %}
                                        <li><a href="{% url 'staff:staff'%}">Staff</a></li>
                                    {% endif %}
                                    {% if not request.user.is_authenticated %}
                                    <li><a href="{% url 'account_login' %}" style="color: #7fad39">Login</a></li>
                                    {% else %}
                                    <li><a href="{% url 'account_logout' %}" style="color: #7fad39">Logout</a></li>
                                    {% endif %}
                                    
                        </ul>
                        </nav>
                        <!--                            <li><a href="#"> <h5 class="pl-3 text-bottom"style="float:right; color:#7fad39;">Login</h5></a></li>
-->
                </div>
                <div class="col-lg-3 pt-4">
                    <div class="header__cart">
                        <ul>   
                            <li><a href="{% url 'account' %}" style="color:black;"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="{% url 'order' %}" style="color:black;"><i class="fa fa-history"></i> Order</a></li>
                            <li><a href="{% url 'cart:summary'%}" style="color:black;"><i class="fa fa-shopping-bag"></i> Cart</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!--Header End-->


<!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                <span class="alert-inner--text">{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>
                {% endfor %}
            {% else %}
                {% for message in messages %}
                <div style="background-color:#cc3300;color:white;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                <span class="alert-inner--text">{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>
                {% endfor %}
            {% endif %}

            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All categories</span>
                        </div>
                            <ul>
                                {% for category in categories %}
                                    <li><a href="/cart/shop/?category={{ category.name }}">{{ category.name }}</a></li>
                                {% endfor %}                        
                            </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">

                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+60 11-1122 9611</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

<div class=container>
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
</div>    

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

templates/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SurFood {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> 
<body>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="/"><img src="/static/img/logo1.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="{% url 'account' %}" style="color:black;"><i class="fa fa-user"></i> Account</a></li>
                <li><a href="{% url 'order' %}" style="color:black;"><i class="fa fa-history"></i> Order</a></li>
                <li><a href="{% url 'cart:summary'%}" style="color:black;"><i class="fa fa-shopping-bag"></i> Cart</a></li>
            </ul>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li id='Home_Header' class="active"><a href="/">Home</a></li>
                <li><a href={% url 'cart:product-list' %}>Shop</a></li>
                <li><a href="{% url 'cart:summary'%}">Shopping Cart</a></li>
                <li><a href="/contact/">Contact</a></li>
                {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff'%}">Staff</a></li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}" style="color: #7fad39">Login</a></li>
                {% else %}
                <li><a href="{% url 'account_logout' %}" style="color: #7fad39">Logout</a></li>
                {% endif %}

            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
    </div>

    <!--Hamburger End-->
    <!--Header Start-->
    <header class="header">
        <div class="header__top">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="/"><img src="/static/img/logo1.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu pt-5 pl-2">
                        <ul>
                                    <li class=""><a href="/">Home</a></li>
                                    <li><a href={% url 'cart:product-list' %}>Shop</a></li>
                                </li>
                                <li><a href="{% url 'contact' %}">Contact</a></li>
                                    {% if request.user.is_staff %}
                                        <li><a href="{% url 'staff:staff'%}">Staff</a></li>
                                    {% endif %}
                                    {% if not request.user.is_authenticated %}
                                    <li><a href="{% url 'account_login' %}" style="color: #7fad39">Login</a></li>
                                    {% else %}
                                    <li><a href="{% url 'account_logout' %}" style="color: #7fad39">Logout</a></li>
                                    {% endif %}
                                    
                        </ul>
                        </nav>
                        <!--                            <li><a href="#"> <h5 class="pl-3 text-bottom"style="float:right; color:#7fad39;">Login</h5></a></li>
-->
                </div>
                <div class="col-lg-3 pt-4">
                    <div class="header__cart">
                        <ul>
                            <li><a href="{% url 'account' %}" style="color:black;"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="{% url 'order' %}" style="color:black;"><i class="fa fa-history"></i> Order</a></li>
                            <li><a href="{% url 'cart:summary'%}" style="color:black;"><i class="fa fa-shopping-bag"></i> Cart</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!--Header End-->


<!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                <span class="alert-inner--text">{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All categories</span>
                        </div>
                            <ul>
                                {% for category in categories %}
                                    <li><a href="/cart/shop/?category={{ category.name }}">{{ category.name }}</a></li>
                                {% endfor %}                        
                            </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+60 11-1122 9611</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                    <div id="carouselExampleControls" class="hero__item carousel slide" data-ride="carousel">
                        <div class="carousel-inner hero__text">
                            <div class="carousel-item active">     
                                <img src="static/img/hero/banner.jpg" class="carousel-img" alt="...">
                                <div class="carousel-content">
                                    <span>GROCERIES</span>
                                    <h2>SURPLUS FOODS <br />100% Edible</h2>
                                    <p>Free Pickup and Delivery Available</p>
                                    <a href="/cart/shop" class="primary-btn">SHOP NOW</a>    
                                </div>
                            </div>
                            <div class="carousel-item">     
                                <img src="static/img/hero/banner2.jpg" class="carousel-img" alt="...">
                                <div class="carousel-content">
                                    <span>PREVENT FOOD WASTE</span>
                                    <h2>SAVE THE WORLD <br />REDUCE GREENHOUSE GASES</h2>
                                    <p style="color:white; font-weight:bold">Food Waste contributed to 10% of greenhouse emission.</p>
                                    <a href="/cart/shop" class="primary-btn">SHOP NOW</a>    
                                </div>
                            </div>
                        </div>
                        
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

<div class=container>
    {% include 'index.html'%}
    {% include 'footer.html' %}
</div>    

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

templates/footer.html
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="/static/img/logo1.png" alt=""></a>
                        </div>
                        <ul class="text-center">
                            <li>This is a Final Year Project </li>
                            <li>proposed by <span  style="font-weight:bold;">TAN MING HO</span></li>
                            <li>Phone: +65 011-11229611</li>
                            <li>Email: tmh0249@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6 class="mobile-title-useful">Useful Links</h6>
                        <div class="mobile-useful">
                        <ul class="text-center">
                            <li><a href="/">Home</a></li>
                            <li><a href={% url 'cart:product-list' %}>Shop</a></li>
                            <li><a href={% url 'contact' %}>Contact Us</a></li>
                        </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="footer__widget text-center">
                        <h6>Objective of SurFood</h6>
                        <p style="justify-content:center">The objective of SurFood is to reduce food wastage by redistributing surplus and expiring foods. Nowaways, most of the supermarkets come with mark down zone to sell expiring items, but somehow these items are not available in online store and has a very low social exposure. SurPlus is an online portal that focusing on selling surplus and expiring foods, which allows customer to purchase expiring foods at a highly-discounted price and pick-up the items at desired store.</p>
                        <div class="footer__widget__social">
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </footer>

templates/order.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black text-center pb-3" style="font-weight:bold">Order</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                        <th>Collect Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>RM{{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                        <td>{% if order.collected %}Yes{% else %}No{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/order_collect.html
{% comment %} {% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="site-section">
        <div class="container pt-3 pb-5">
            <div class="row justify-content-center">
                <div class="col-md-7 pb-4">
                    <h2 class="h3 mb-3 text-black text-center">Product Collect Status</h2>
                </div>
                <div class="col-md-12 justify-content-center pb-4"> 
                  <h3 class="h5 mb-3 text-center">Are you sure the item has been collected?</h3>
               </div>
                <div class="col-md-2">
                  <form method="post">
                    {% csrf_token %}
                    {{ form|crispy}}
                    <button type='submit' class='btn btn-primary'>Yes</button>
                    <a href="{% url 'staff:staff' %}" class='btn btn-primary'>Cancel</a>
                  </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %} {% endcomment %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black text-center pb-3" style="font-weight:bold">Your profile</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td>#{{ order.reference_number }}</td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/scripts.html
{% load static %}
   
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>   